Update requirements.txt
TensroboardX [newest release 1.7](https://github.com/pytorch/ignite/issues/534) is no longer working with our implementation.

```Loading training set: 100%|███████████████████████| 3/3 [00:35<00:00, 11.59s/it]
Loaded 1360 axial slices for the training set.
Loading validation set: 100%|█████████████████████| 1/1 [00:11<00:00, 11.86s/it]
Loaded 655 axial slices for the validation set.
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p112175/anaconda3/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/GRAMES.POLYMTL.CA/p112175/test/ivadomed/main.py", line 421, in run_main
    cmd_train(context)
  File "/home/GRAMES.POLYMTL.CA/p112175/test/ivadomed/main.py", line 180, in cmd_train
    writer = SummaryWriter(log_dir=context["log_directory"])
  File "/home/GRAMES.POLYMTL.CA/p112175/anaconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/home/GRAMES.POLYMTL.CA/p112175/anaconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'```


This can be fixed by imposing `tensorboardX==1.6` in the `requirements.txt` file.